server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: ${ACCESS_LOG:/Users/honggao.chen/IdeaProjects/guide/logs}
      pattern: common
      prefix: access_log
      suffix: log
spring:
  application:
    name: simple-app

logging:
  level:
    cn.simple: DEBUG